### PR TITLE
Fix for JGit unable to parse HEAD:branch

### PR DESCRIPTION
**Pull request by kristian**
See [JENKINS-20393](https://issues.jenkins-ci.org/browse/JENKINS-20393) for details.

### CODE REVIEW

**Comment by MarkEWaite** [comment]
I was hoping to hide the 5 commit steps we took to arrive at a working solution, since I don't think the steps are especially informative to others reading the code.  What I had in mind is more like 813a6096f75aed90724190436eb099f54d192b25, a single commit which smashes all 5 of these commits into one.

**Comment by kristian** [comment]
Hey Mark, I tired to squash the commit stogether, as you suggested... Unfortunately the pull fails now, any suggestion?

**Comment by MarkEWaite** [comment]
I think you need to perform the squash based on the tip of the current master branch.  The failing jenkins job is reporting that the merge with the current master branch failed due to conflicts.

You could also compare the result of the squash with 813a6096f75aed90724190436eb099f54d192b25 to see if there are relevant differences between your commit (with your correct author information) and my prototype commit.

Yesterday I found a few cases that were not being tested (force and timeout) so I improved the tests in 6319b71a4906229fb92a87c986b237a250d0f4dd .  I'd be very grateful if you could code review that proposed commit, since it is a larger test change than my previous changes.

**Comment by kristian** [comment]
Strange I had to merge my fork with the upstream, even though it was a fast-foward / recursive merge. I always thought GitHub would be able to do those on it's own, when creating a pull request. Oh well.

I have also reviewed your ``Push(Simple)?Test`` classes, especially the changes you did in [``6319b71``](https://github.com/jenkinsci/git-client-plugin/commit/6319b71a4906229fb92a87c986b237a250d0f4dd), I really like the way you utilized the ``@Parameterized.Parameters``, but isn't shuffling a bit unnecessary as you do anyways test all permutations of ``implementations`` and ``good/badRefSpec``?

**Comment by MarkEWaite** [comment]
Yes, the shuffle ultimately proved to be unnecessary.  I've had cases in the past where order dependencies unexpectedly exposed a problem in the code.  The shuffle calls are only minor safeguards.

**Comment by kristian** [comment]
Sounds fair to me. :+1: Good job.

**Comment by MarkEWaite** [comment]
It's on the master branch, will be included in the next git client plugin after 1.18.0

**Comment by kristian** [comment]
Great, thanks a lot for your support.

**Pull request closed without merging**
