### PR TITLE
Enable FindBugs report generation on verify stages

### PR DESCRIPTION
**Pull request by oleg-nenashev**
It will allow to setup FindBugs reporting or to enforce the code requirements on https://jenkins.ci.cloudbees.com/job/plugins/job/git-client-plugin/

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Can you explain further what I should have seen when I merged this into the git client plugin?

I merged it, then ran "mvn clean install" and was expecting to see some reference to the execution of findbugs as part of the verify stage (which is a predecessor to the install phase).  There was no mention of findbugs in that run.

I ran "mvn clean verify install" and also did not see any reference to findbugs execution in the build output.

**Comment by KostyaSha** [comment]
@MarkEWaite FYI you can just git checkout merged state of PR that is updated every time when target branch updated.

**Comment by MarkEWaite** [comment]
@KostyaSha I used the "merge branches on the command line" instructions embedded in this page and confirmed that the changes were visible in the local resulting branch.  When I did that and ran "mvn clean install", the findbugs plugin did not run.

Since it does seem to run on the link that Oleg provided, I assume that https://jenkins.ci.cloudbees.com/job/plugins/job/git-client-plugin/ must be explicitly executing the findbugs:check maven goal.  Alternately, I still have more to learn about maven and don't quite understand how to invoke "mvn clean install" in a way that will include the verify phase.

**Comment by oleg-nenashev** [comment]
@MarkEWaite 
My apologies, I've added the code to <code>pluginManagement</code> instead of <code>plugins</code>, so it runs differently depending on Maven profiles. I'll fix it.

**Comment by KostyaSha** [comment]
@MarkEWaite i mean that you can avoid 'I merged it onto a private development branch' if it only for single PR check.

Plugin in wrong section.

**Comment by oleg-nenashev** [comment]
@MarkEWaite @KostyaSha 
The issue has been fixed (see above)

**Pull request merged**
