### PR TITLE
[JENKINS-20941] Incomplete progress towards using credentials for "submodule add" and "submodule update"

### PR DESCRIPTION
**Pull request by steven-collins-omega**
I don't necessarily expect this pull request to be accepted as-is, as I didn't add any tests, and I don't have time to do so currently. It does seem to work, though, and doesn't break any existing submodule tests.

### CODE REVIEW

**Comment by iMerica** [comment]
What is the temporary workaround for this when running Jenkins on a Mac?

**Comment by MarkEWaite** [comment]
I'm not a submodule user with git, and I'm not a Mac user, so these comments are only guesses.  

* You might try embedding read-only credentials in the submodule URL in the git repository, or
* configure the Jenkins user on master and on each slave so that git without credentials can successfully read from the submodules (ssh configuration, etc.)

**Comment by bemsha** [comment]
Please re-open this issue.

Embedding credentials in code or in the Jenkins configuration are not adequate workarounds.

**Comment by MarkEWaite** [comment]
@bemsha, I'm not sure what you intend as the action to be associated with "please re-open this issue".  Can you explain in more detail?

Are you expecting that "re-open this issue" means that someone will implement support for credentials in submodules?  If so, who will do that?

There is already an enhancement request in Jira for this, and it is the most requested enhancement for the git plugin.  Unfortunately, it also seems difficult to implement.

**Comment by bemsha** [comment]
Where's the enhancement request?

      Chuck Karish             chuck@nextdoor.com               650 283 7864

**Comment by steven-collins-omega** [comment]
I finally changed the title of this, which I should have done a year ago. For some reason I was under the impression I couldn't change it. Sorry.

I still think the original pull request could at least be a small start toward something that would work in 95% of cases, and of course anyone is welcome to take what I started and run with it.

**Comment by shuckc** [comment]
You can explicitly provide the credentials as follows:

```stage ('Clone') {
            steps {
                checkout scm
                withCredentials([sshUserPrivateKey(credentialsId: 'bitbucket_ssh', keyFileVariable: 'SSH_KEY')]) {
                    sh 'GIT_SSH_COMMAND="ssh -i $SSH_KEY" git submodule update --init'
                }
            }
        }```

**Pull request closed without merging**
