### PR TITLE
Require 2.426.3 as minimum Jenkins version

### PR DESCRIPTION
**Pull request by AniketNS**
## Require 2.426.3 as minimum Jenkins version

Jenkins 2.426.3 is now one of the recommended versions in the [Jenkins documentation](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/).  Jenkins 2.426.3 includes an important [security fix](https://www.jenkins.io/security/advisory/2024-01-24/#SECURITY-3314) that should motivate more users to install it or a newer version.

* 96% of the over 49000 installations of the most recent release are running on 2.426.3 or newer
* 75% of the over 71000 installations of the second most recent release (4.6.0) are running on 2.426.3 or newer

Summary:

The vast majority of users that are installing the most recent release of the git client plugin are already running Jenkins 2.426.3 or newer.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-client-plugin/blob/master/CONTRIBUTING.adoc) doc
- [x] Unit tests pass locally with my changes
- [x] No Javadoc warnings were introduced with my changes
- [x] No spotbugs warnings were introduced with my changes
- [x] I have interactively tested my changes

## Types of changes

What types of changes does your code introduce?

- [x] Infrastructure change (non-breaking change which updates dependencies or improves infrastructure)

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks for the pull request @AniketNS .  The pull request has some gaps that you can use on your journey of learning about git, GitHub, and pull requests.

* The pull request includes many extra commits that are unrelated to the pull request.  Those extra commits are a distraction to reviewers and can reduce the chances that your pull request will be reviewed.  The extra commits indicate that you started your pull request from a git commit that is not the tip of the destination (master) branch.  It is best to always start a pull request from the tip of the destination branch.  Commands that I use to always start a commit from the tip of the destination master branch include:
    ```
    # Adding remote is only needed once
    git remote add upstream https://github.com/jenkinsci/git-client-plugin.git
    # Retrieve latest changes from all remote repositories
    git fetch --all
    # Start the new branch from the upstream master branch
    git checkout -b new-branch-name upstream/master
    # Submit the new branch to GitHub
    git push --set-upstream origin new-branch-name
    ```
* The pull request description doesn't tell me (the maintainer) why you are making this change.  It has a very good summary "Require Jenkins 2.426.3 as minimum Jenkins version" (good job with that!).  It uses the pull request template (very good!). 
 However, it is not clear what motivated the change.  If you were using the ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/step ["Update base Jenkins version"](https://www.jenkins.io/doc/developer/tutorial-improve/update-base-jenkins-version/) then it is good to include a link to the tutorial

If you'd like to use the pull request to learn more about git and about GitHub pull requests, you can resolve the conflict with the destination branch and submit the additional commits that resolve the conflict.  Some of the commands that you'll need to use to resolve the conflict include:

```
git fetch --all
git merge upstream/master
git diff upstream/master
mvn clean verify
```

If you'd rather close the pull request and submit a new pull request, that is fine as well.

**Comment by AniketNS** [comment]
Yeah I'll do that @MarkEWaite. Thanks for the feedback

**Comment by MarkEWaite** [comment]
For this specific commit, there is also a very useful data source that some maintainers use to decide when they will upgrade the minimum required Jenkins version.  The Jenkins documentation page ["Choosing a Jenkins version to build against"](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/) provides the guidelines and instructions to help maintainers choose a new Jenkins base version.  In addition to those instructions, each plugin has a link to "View detailed version information" on its [plugins.jenkins.io page](https://plugins.jenkins.io/git-client/). 

For the git client, the [detailed version information page](https://stats.jenkins.io/pluginversions/git-client.html) shows the following information when hovering over various parts of that page:

* Over 285000 total installations of the plugin (lower right corner)
    * 40% of all git client plugin installations are running on Jenkins 2.426.3 or newer (hover over the right-most cell of the 2.426.3 row).
* Over 49000 installations of the most recent release (4.7.0)
    * 96% of the over 49000 installations of the most recent release are running on 2.426.3 or newer (hover over the cell at the intersection of row "2.426.3" and column "4.7.0")
* Over 71000 installations of the second most recent release (4.6.0)
    * 75% of the over 71000 installations of the second most recent release (4.6.0) are running on 2.426.3 or newer (hover over the cell at the intersection of row "2.426.3" and column "4.6.0")

**Comment by AniketNS** [comment]
Thanks for the detailed feedback @MarkEWaite and the detailed information about the code.
>The pull request includes many extra commits that are unrelated to the pull request.

That's true but, I didn't understand why, even if I create a different branch those older commits are coming in the way. But I didn't see any code from those commits that's why It didn't trigger me.

>However, it is not clear what motivated the change. If you were using the ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/step ["Update base Jenkins version"](https://www.jenkins.io/doc/developer/tutorial-improve/update-base-jenkins-version/) then it is good to include a link to the tutorial

I was indeed using the [Update Jenkins version](https://www.jenkins.io/doc/developer/tutorial-improve/update-base-jenkins-version/) and that's why I made that change. I would've mentioned that in the PR description.

>For this specific commit, there is also a very useful data source that some maintainers use to decide when they will upgrade the minimum required Jenkins version. The Jenkins documentation page ["Choosing a Jenkins version to build against"](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/) provides the guidelines and instructions to help maintainers choose a new Jenkins base version. In addition to those instructions, each plugin has a link to "View detailed version information" on its [plugins.jenkins.io page](https://plugins.jenkins.io/git-client/).

I read the document, but as a newbie, I didn't understand a thing from [Choosing a Jenkins version to build against](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/) but looked into [detailed version information page](https://stats.jenkins.io/pluginversions/git-client.html) and it was kinda interesting and got some nice info about git-client plugin versions, updates and it's downloads.

I've somehow removed the conflict. Tell me if there's anything I should change. Thanks.

**Comment by MarkEWaite** [comment]
> even if I create a different branch those older commits are coming in the way

That likely means your local copy is out of sync with the upstream repository or is out of sync with your fork of the upstream repository.  One simple way to fix that is to rename your local repository to and clone it again.

**Comment by AniketNS** [comment]
> That likely means your local copy is out of sync with the upstream repository or is out of sync with your fork of the upstream repository. One simple way to fix that is to rename your local repository to and clone it again.

Ohh ok @MarkEWaite. I'll look more into git commands.

**Review by MarkEWaite — APPROVED** [review]
Ready to merge.  Git plugin 5.2.2 was released recently and requires Jenkins 2.426.3 or newer.  Next release date of git client plugin is not yet decided, but it makes sense that the next release require Jenkins 2.426.3 or newer.

**Pull request merged**
