### PR TITLE
implement repos.json to replace repos.csv

### PR DESCRIPTION
**Pull request by jacob-keller**
Obviously, a new repos.json file will be required as compared to the current repos.csv.

This format is much more manageable, and extendable. Possibly we want to change the whole way we handle items in it instead of returning an object and using the items to populate a constructor, we should maybe pass the entire thing as a Map. However, I didn't bother with that just yet.

I did add two new features that are optional to the list, submodule checkout support, and file testing, to not hardcode the README.md

Hopefully this is a solid addition that can be pulled without much fuss, as these changes will be helpful in testing the related issues with the submodule and HTTP changes.

### CODE REVIEW

**Comment by jacob-keller** [comment]
If the test harness on Jenkins uses a repos.csv file, it will need to be updated to use a repos.json file, and the checks won't really indicate proper coverage of these changes.

**Comment by MarkEWaite** [comment]
The defaultPrivateKey section of the test does not include the correct number of arguments to pass the test. Once I added the new arguments, the test (with no repos.json) passed on my Ubuntu machine. It is running through my other machines currently (with no repos.json).

The test harness on the Cloudbees server does not provide a repos.csv file.  My home test environment is the only location which I know provides a repos.csv file.

As part of evaluating the pull request, I'll convert my repos.csv file into a repos.json file.  Once the conversion is complete and verified on one computer, I'll push it to all the other test machines so that it is evaluated on Windows,  Ubuntu, CentOS, and Debian with various git versions.

**Comment by jacob-keller** [comment]
Oh that is what I was missing. I couldn't figure out how that was happening. Ok, I can clean that up in my series and submit a forced-push update.

**Comment by MarkEWaite** [comment]
No need for you to make that change.  There were also formatting changes needed in order to keep the formatting inside the file consistent.  I'm running a modified version of the pull request through tests now, then will rebase my changes onto yours into a single commit.

**Comment by jacob-keller** [comment]
Feel free to squash things in if you like :)

**Comment by MarkEWaite** [comment]
I also found that the checks which were skipping rows with incomplete data were causing tests which I'd intentionally defined to be skipped.  So long as the data includes a repository URL, it should be used for a test.  There are URL forms which embed the username and password into the URL, others which embed only the username.

**Comment by jacob-keller** [comment]
Ok that makes sense I wasn't sure but the old way made sure to have enough
fields so I just added checks for all the fields.

Regards
Jake

**Comment by MarkEWaite** [comment]
Rebased and merged into master branch

**Pull request closed without merging**
