### PR TITLE
Make git-client compatible with future guava

### PR DESCRIPTION
**Pull request by timja**
See https://github.com/jenkinsci/bom/pull/423

and example merged PR in a pipeline component: https://github.com/jenkinsci/workflow-support-plugin/pull/114

cc @MarkEWaite

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by timja** [comment]
@MarkEWaite could you release this please?

**Comment by MarkEWaite** [comment]
> @MarkEWaite could you release this please?

Sure, though I want some interactive test time before I release it.  I will want to release git plugin as well, since it also increases its minimum Jenkins version to 2.249.1, just as the master branch of the git client plugin does.

**Comment by timja** [comment]
sure you can hold off a bit anyway, I'm going to try a no reflection approach based off of https://github.com/jenkinsci/workflow-support-plugin/pull/117

**Comment by timja** [comment]
think I'll leave it a lot of classes need vendoring unless @basil wants to give it a go?

**Comment by basil** [comment]
Vendoring `DirectExecutorService` seems like more trouble than it's worth. This solution seems fine.

**Comment by MarkEWaite** [comment]
@timja and @basil I'd like to wait until the official release of JGit 5.11.0 on 17 Mar 2021 before this is released.  That also allows me a few days to re-evaluate the user impact of #673.  It adds more noise to the console log and provide benefit to a very narrow set of users.

**Comment by timja** [comment]
makes sense looks like that PR should be tweaked, will follow up later on if required

**Comment by MarkEWaite** [comment]
Released as [git client plugin 3.7.0](https://github.com/jenkinsci/git-client-plugin/releases/tag/git-client-3.7.0) 17 Mar 2021

**Pull request merged**
