### PR TITLE
Improve the CONTRIBUTING file and matching code changes

### PR DESCRIPTION
**Pull request by MarkEWaite**
@stephenc commented on the power of a good CONTRIBUTING file to guide people as they submit pull requests.  This is my attempt to make some progress toward having a CONTRIBUTING file in the git client plugin which clearly expresses the guidelines for the plugin.

I think guidelines should only be added to the CONTRIBUTING file when the plugin source code actually complies with the guidelines.  Thus, this initial effort states very few guidelines.

I'd like a @reviewbybees to see if others think that is a reasonable approach for the git client plugin

### CODE REVIEW

**Comment by stephenc** [comment]
:+1: on any improvements to a `CONTRIBUTING.md` (or better yet a `CONTRIBUTING.adoc`)

**Comment by KostyaSha** [comment]
> (or better yet a CONTRIBUTING.adoc)

https://help.github.com/articles/setting-guidelines-for-repository-contributors/ documentation doesn't reference to adoc, is it supported?

**Comment by stephenc** [comment]
> https://help.github.com/articles/setting-guidelines-for-repository-contributors/ documentation doesn't reference to adoc, is it supported?

Well `CONTRIBUTING.asc` works... and I just checked that the preferred ascidoc extension also works... try creating a pull request against https://github.com/cloudbeers/yolo

**Comment by oleg-nenashev** [comment]
:+1: for the improvement. md/adoc have a similar functionality, so both work for me.

Regarding the newly developed code I would...
* Explicitly specify the recommended formatting guidelines (e.g. [Oracle codestyle](http://www.oracle.com/technetwork/java/codeconvtoc-136057.html))
* Recommend/require using <code>@CheckForNull</code> annotations (and probably <code>@Nonnull</code>)
* Require unit tests for new functionality and fixes of a functional bugs
* Require Javadoc for new API methods

**Comment by stephenc** [comment]
@oleg-nenashev perfect is the enemy of done.

Starting small and growing from there is better than trying to get it all in one go. With the repositories where I am maintainer I have the luxury of being closer to the current guidelines I'm pushing so I can cram more in

**Comment by MarkEWaite** [comment]
@oleg-nenashev, I'm aligned with @stephenc on this one.

It was a conscious choice to only include things in the code style guidelines section which the code actually honors throughout. That's why there is such a long paragraph about code formatting and why the addition of the mvn tidy:pom guideline required a white space only change to pom.xml.

I'm starting small with things that I believe are fully implemented, and will (hopefully) steadily add more fully implemented improvements.

**Comment by KostyaSha** [comment]
:+1: But according to my experiments `mvn tidy:pom` doesn't change sections order.

**Comment by KostyaSha** [comment]
> Well CONTRIBUTING.asc works... and I just checked that the preferred ascidoc extension also works... try creating a pull request against https://github.com/cloudbeers/yolo

I see, it's enough to press new Issue.

**Comment by MarkEWaite** [comment]
@KostyaSha when I ran mvn tidy:pom it moved the repositories section of the pom earlier in the file.

**Comment by aheritier** [comment]
In the past I used the maven sortpom plugin like here : https://github.com/exoplatform/maven-parent-pom/blob/master/pom.xml#L1482
I found it more efficient/powerful that the tidy pom plugin

**Comment by MarkEWaite** [comment]
I wasn't aware of the sortpom plugin.  The greater control it provides looks very interesting, especially the automatic formatting of the pom as part of each build.

**Pull request merged**
