### PR TITLE
Tolerate default commit signing with SSH in tests

### PR DESCRIPTION
**Pull request by jtnord**
## Tolerate default commit signing with SSH in tests

work around https://bugs.eclipse.org/bugs/show_bug.cgi?id=581483

If the current git setup has SSH based code signing enabled (gpg.format=ssh)[1] then the tests fail (even though not signing) as jgit fails to parse the config with an error like:

```
java.lang.IllegalArgumentException: Invalid value: gpg.format=ssh
        at org.eclipse.jgit.lib.DefaultTypedConfigGetter.getEnum(DefaultTypedConfigGetter.java:103)
        at org.eclipse.jgit.lib.Config.getEnum(Config.java:454)
        at org.eclipse.jgit.lib.GpgConfig.<init>(GpgConfig.java:86)
        at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:662)
        at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:189)
        at org.jenkinsci.plugins.gitclient.JGitAPIImpl.commit(JGitAPIImpl.java:487)
        at org.jenkinsci.plugins.gitclient.GitClientMaintenanceTest.commitFile(GitClientMaintenanceTest.java:230)
        at org.jenkinsci.plugins.gitclient.GitClientMaintenanceTest.commitOneFile(GitClientMaintenanceTest.java:224)
        at org.jenkinsci.plugins.gitclient.GitClientMaintenanceTest.commitSeveralFiles(GitClientMaintenanceTest.java:218)
        at org.jenkinsci.plugins.gitclient.GitClientMaintenanceTest.test_gc_maintenance(GitClientMaintenanceTest.java:333)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

[1] https://git-scm.com/docs/git-config#Documentation/git-config.txt-gpgformat

This has only been tested on my local windows development environment. before this change, tests failed as above.

After this change the only failing test is 
```
 GitClientTest.test_git_ssh_executable_found_on_windows:3393 » Runtime ssh executable not found. The git plugin only supports official git client https://git-scm.com/download/win
```
which is a lie, but somewhat expected as this installation of the official git client did not install ssh or any mysys tools.

## Checklist

- [x] Unit tests pass locally with my changes

## Types of changes

What types of changes does your code introduce?

- [x] Test fix (non-breaking change which updates dependencies or improves infrastructure)

### CODE REVIEW

**Comment by MarkEWaite** [comment]
@jtnord I pushed changes that allow the pull request to pass tests in my environments (Linux, Windows, FreeBSD, etc.) and should pass tests on ci.jenkins.io.  Could you test the most recent changes on your Windows environment?

**Comment by MarkEWaite** [comment]
@jtnord I'm out of office for the next week but may have time for further reviews and changes.  I see a pattern of repeating code in those tests that I would like to fix, if you're OK with me using this draft pull request to improve the tests.  I would need you to tell me if the tests that I've modified still pass on your Windows computer.

**Comment by jtnord** [comment]
@MarkEWaite all[1]  tests pass, however something is still missing the `--local` and messing with the actual clone of the repo.

after running tests my clone has the following new config options ->

```
commit.gpgsign=false
tag.gpgsign=false
gpg.format=openpgp
```

Which is unrelated to the tolleration of `ssh` commit signing, but if you are also looking to cleanup / refactor local setting may be something to look at at the same time,

[1] with the exception of `GitClientTest.test_git_ssh_executable_found_on_windows:3393` which is somewhat expected for my environment given the test.

**Comment by MarkEWaite** [comment]
> after running tests my clone has the following new config options ->
> 
> ```
> commit.gpgsign=false
> tag.gpgsign=false
> gpg.format=openpgp
> ```
> 
> Which is unrelated to the toleration of `ssh` commit signing, but if you are also looking to cleanup / refactor local setting may be something to look at at the same time,

Thanks.  I've previously accepted persistent changes in the configuration of the working repository to support tests, but this may be the ideal time to fix that poor behavior.

**Comment by jtnord** [comment]
@MarkEWaite pklease `@mention` me when you would like me to run the tests locally again.

**Comment by MarkEWaite** [comment]
@jtnord I've fixed the duplications that I had created in the tests.  I've run the tests successfully on my Linux machine from a user configuration that has GPG signing enabled globally and I've run them successfully on my Linux and Windows machines where GPG signing is not enabled.  Could you check them as well?

@olamy I don't want to disrupt your work on the switch from trilead to Apache Mina.  Once this has been reviewed and verified by @jtnord, I'm happy to wait until your work on the switch from trilead to Apache Mina is complete  If you find that these changes won't disrupt your work on the switch from trilead to Apache Mina, they can be merged as soon as they are confirmed to pass tests in all the desired configurations.

Thanks again to both of you!

**Review by MarkEWaite — APPROVED** [review]

**Review by olamy — APPROVED** [review]

**Comment by olamy** [comment]
@MarkEWaite no worries at all. the changes in this PR are different from my current work from now
Better to do this now as I may change those classes (`*Test*`) as well later next week :)

**Comment by jtnord** [comment]
tests all pass locally with the exception of the known `GitClientTest.test_git_ssh_executable_found_on_windows` 

However it is still modifying my local config.
```
commit.gpgsign=false
tag.gpgsign=false
```

```
[ERROR] Errors:
[ERROR]   GitClientTest.test_git_ssh_executable_found_on_windows:3371 » Runtime ssh executable not found. The git plugin only supports official git client https://git-scm.com/download/win
```

```
❯ ssh -V
OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

❯ where ssh
C:\Windows\System32\OpenSSH\ssh.exe
```

**Comment by olamy** [comment]
yup confirmed as well.
grhh need to go to almost every test changing the config :(

**Pull request merged**
